aliases: []
creation_timestamp: 1736500088940
current_stage: Production
description: null
last_updated_timestamp: 1736755715162
name: spacy_en_core_web_sm
run_id: 4cfcbbb12cec431090c5fe97265f494e
run_link: null
source: file:///home/hedredo/github/p7/notebooks/mlruns/0/4cfcbbb12cec431090c5fe97265f494e/artifacts/spacy_en_core_web_sm
status: READY
status_message: null
storage_location: file:///home/hedredo/github/p7/notebooks/mlruns/0/4cfcbbb12cec431090c5fe97265f494e/artifacts/spacy_en_core_web_sm
user_id: null
version: 1
