aliases: []
creation_timestamp: 1736755520086
current_stage: Production
description: null
last_updated_timestamp: 1736755633143
name: neuralnet
run_id: null
run_link: null
source: ../mlruns/9/15c36d2a681f47219f7b77774ce43838/artifacts/model
status: READY
status_message: null
storage_location: ../mlruns/9/15c36d2a681f47219f7b77774ce43838/artifacts/model
user_id: null
version: 1
