name: Run Unit Tests

on:
  push:
    branches:
      - master  # Exécuter les tests sur chaque commit dans la branche principale
  pull_request:
    branches:
      - master  # Exécuter les tests sur chaque PR ciblant la branche principale

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Installer Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Étape 4 : Exécuter les tests avec logs
      - name: Run unittest with logs
        run: |
          python -m unittest discover tests -v > test_output.log
      # Étape 5 : Télécharger les logs en cas d'échec
      - name: Upload logs
        if: failure()  # Exécute cette étape uniquement en cas d'échec
        uses: actions/upload-artifact@v3
        with:
          name: test-logs
          path: test_output.log
